### ISSUE TITLE
Paper pdf access

### ISSUE THREAD

**Issue by Zehui-Lin** [zhaoziheng/SAT#4]
The paper on arXiv has been withdrawn, and now I can't find a place to download the paper. Could you please explain what happened?

**Comment by zhaoziheng** [comment]
Hi, Zehui. 

Due to the copyright problem in the knowledge data we used, we are retraining our model and the paper has been withdrawn temporarily. Sorry for the inconvenience.

Best Regards,
Ziheng Zhao

**Comment by Zehui-Lin** [comment]
Thank you! Look forward to new published papers and model weights.
