### ISSUE TITLE
problem about environment

### ISSUE THREAD

**Issue by AshleyLuo001** [zhaoziheng/SAT#6]
after setting my environment use the config of readme file，I run the inference command that noted by 
![image](https://github.com/zhaoziheng/SAT/assets/101108252/d9529e5a-2031-4cf7-b4f0-aee003e67ba1)
and the version of my monai is aligned with the requirement.
![image](https://github.com/zhaoziheng/SAT/assets/101108252/25345dbd-0ada-4dc0-b975-2b55dd1f5c64)

**Comment by zhaoziheng** [comment]
Hi. It seems that under monai==1.1.0 I can still use AddChanneld, though got a warning.
<img width="1431" alt="截屏2024-05-08 21 02 53" src="https://github.com/zhaoziheng/SAT/assets/34470357/5f137c86-e696-421a-ba92-bd8e47336267">

**Comment by AshleyLuo001** [comment]
> It seems that using 'EnsureChannelFirstd' instead of 'AddChanneld' works fine.

Thank you！ I get it！
