### ISSUE TITLE
Does the MSD dataset have a script for processing json files?

### ISSUE THREAD

**Issue by AshleyLuo001** [zhaoziheng/SAT#7]
However, when I directly use the json file provided with the MSD dataset I have a problem reading the format mismatch, I would like to know what kind of way the authors use to process the dataset collectively, can you provide me with the data or the script used to process the data?

**Comment by zhaoziheng** [comment]
Hi. We support input data in a jsonl file, you can check the **Inference Guidance** in README and refer to `demo/inference_demo/demo.jsonl` to prepare your data with required format.
