### ISSUE TITLE
Custmized input text

### ISSUE THREAD

**Issue by heyufan1995** [zhaoziheng/SAT#8]
Hi:
Great work! I tried the demo and read the paper and have several questions.
1. will the data "medical domain knowledge to train the text encoder" be released someday?
2. I changed the label from "liver" to "A large organ found in the upper right quadrant of the abdomen" or "A large organ found in the upper right quadrant of the abdomen called liver". The latter two is not working at all. Seems like the text-encoder can only understand "liver", not its description?
Thanks

**Comment by zhaoziheng** [comment]
Hi, thanks for your interest in our work.
1. I have sent you a email about this question, check your gmail please.
2. We assign label name to each anatomical structure or lesion, i.e., their terminology, and use them as the only text prompts when training SAT. Therefore, it does not support "description" so far.

**Comment by heyufan1995** [comment]
Thanks!
